CREATE TABLE USER_INFO(
	USER_ID	 VARCHAR(255) NOT NULL,
	FLAG	Number	NOT NULL,
	USER_NAME	VARCHAR(255) NOT NULL,
	PASSWORD	VARCHAR(255) NOT NULL,
	EMAIL	VARCHAR(255) NOT NULL,
	CONTACT_NUM	NUMBER NOT NULL,
	PROFILE_PATH	VARCHAR(255) NOT NULL,
	BIRTH	Number	NOT NULL,
	CITY	VARCHAR(255)	NOT NULL
);

CREATE TABLE CORPORTAE_USER_METADATA (
	USER_ID	VARCHAR(255) NOT NULL,
	BUSINESS_NUMBER NUMBER	NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	MANAGER_NAME	 VARCHAR(255) NOT NULL,
	MANAGER_CONTACT_NUMBER VARCHAR(255) NOT NULL
);

CREATE TABLE USER_METADATA (
	USER_ID	VARCHAR(255) NOT NULL,
	POSITION_1	VARCHAR(255) NULL,
	POSITION_2	VARCHAR(255) NULL,
	POSITION_3	VARCHAR(255) NULL,
	POSITION_4	VARCHAR(255) NULL,
	POSITION_5	VARCHAR(255) NULL,
	LAN_1	VARCHAR(255) NULL,
	LAN_2	VARCHAR(255) NULL,
	LAN_3	VARCHAR(255) NULL,
	FRAMEWORK_1	VARCHAR(255) NULL,
	FRAMEWORK_2	VARCHAR(255) NULL,
	FRAMEWORK_3	VARCHAR(255) NULL,
	EXP	VARCHAR(255) NULL,
	PERIOD	VARCHAR(255) NULL,
	DBS_1	VARCHAR(255) NULL,
	DBS_2	VARCHAR(255) NULL,
	DBS_3	VARCHAR(255) NULL
);

CREATE TABLE USER_RESUME (
	RESUME_ID	VARCHAR(255) NOT NULL,
	INTRODUCTION_IMG_PATH	VARCHAR(255) NULL,
	INTRODUCTION_HEADER	VARCHAR(255) NULL,
	INTRODUCTION_MAIN	VARCHAR(255)	NULL,
	SKIL_SET_FIRST	VARCHAR(255)	NULL,
	SKIL_SET_SECOND	VARCHAR(255)	NULL,
	SKIL_SET_THIRD	VARCHAR(255)	NULL,
	SKIL_SET_FORTH	VARCHAR(255)	NULL,
	SKIL_SET_FIFTH VARCHAR(255)	NULL,
	SKIL_SET_SIXTH	VARCHAR(255)	NULL,
	SKIL_SET_SEVENTH	VARCHAR(255)	NULL,
	SKIL_SET_EIETH	VARCHAR(255)	NULL,
	CONTACT_INFO_BIRTH	VARCHAR(255)	NULL,
	CONTACT_INFO_CITY	VARCHAR(255)	NULL,
	PORTFOLIO_FIRST_IMG	VARCHAR(255)	NULL,
	PORTFOLIO_FIRST_GITHUB	VARCHAR(255)	NULL,
	PORTFOLIO_FIRST_NAME	VARCHAR(255)	NULL,
	PORTFOLIO_SECOND_GITHUB	VARCHAR(255)	NULL,
	PORTFOLIO_SECOND_IMG	VARCHAR(255)	NULL,
	PORTFOLIO_SECOND_NAME	VARCHAR(255)	NULL,
	PORTFOLIO_THIRD_IMG	VARCHAR(255)	NULL,
	PORTFOLIO_THIRD_GITHUB	VARCHAR(255)	NULL,
	PORTFOLIO_THIRD_NAME	VARCHAR(255)	NULL,
	BLOG_ADDRESS	VARCHAR(255) NULL,
	GITHUB_ADDRESS	VARCHAR(255) NULL,
	FACEBOOK_ADDRESS VARCHAR(255)	NULL,
	INSTAGRAM_ADDRESS VARCHAR(255)	NULL,
	TEMPLATE_KIND VARCHAR(255)	NULL,
	USER_ID	VARCHAR(255) NOT NULL,
	Disclosurestatus NUMBER NOT NULL
);

CREATE TABLE COMPANY_INTRO_DETAIL (
	USER_ID	 VARCHAR(255) NOT NULL,
	LOGO_IMG	VARCHAR(255)	NULL,
	STAFF_NUMBER	Number	NOT NULL,
	WELFARE_1	VARCHAR(255)	NULL,
	WELFARE_2	VARCHAR(255)	NULL,
	WELFARE_3	VARCHAR(255)	NULL,
	SUMMARY VARCHAR(255)	NOT NULL
);

ALTER TABLE USER_INFO ADD CONSTRAINT PK_USER_INFO PRIMARY KEY (
	USER_ID
);

ALTER TABLE CORPORTAE_USER_METADATA ADD CONSTRAINT PK_CORPORTAE_USER_METADATA PRIMARY KEY (
	USER_ID
);

ALTER TABLE USER_METADATA ADD CONSTRAINT PK_USER_METADATA PRIMARY KEY (
	USER_ID
);

ALTER TABLE USER_RESUME ADD CONSTRAINT PK_USER_RESUME PRIMARY KEY (
	RESUME_ID
);

ALTER TABLE COMPANY_INTRO_DETAIL ADD CONSTRAINT PK_COMPANY_INTRO_DETAIL PRIMARY KEY (
	USER_ID
);

ALTER TABLE CORPORTAE_USER_METADATA ADD CONSTRAINT
FK_INFO_METADATA_1 FOREIGN KEY (
	USER_ID
)
REFERENCES USER_INFO (
	USER_ID
);

ALTER TABLE USER_METADATA ADD CONSTRAINT FK_INFO_TO_METADATA_1 FOREIGN KEY (
	USER_ID
)
REFERENCES USER_INFO (
	USER_ID
);

ALTER TABLE COMPANY_INTRO_DETAIL ADD CONSTRAINT FK_METADATA_DETAIL_1 FOREIGN KEY (
	USER_ID
)
REFERENCES CORPORTAE_USER_METADATA (
	USER_ID
);

